"""Interactive configuration wizard for security scans.

Usage:
    python -m orchestrator.wizard

Guides the user through scope/profile/input selection and generates
the appropriate .env + command line for a scan.
"""
# ⚠️ Contenu généré par IA — validation humaine requise avant utilisation.

from __future__ import annotations

import os
import sys
from pathlib import Path

from orchestrator.profiles import LIGHT_TOOLS, MEDIUM_TOOLS


def _prompt(question: str, options: list[str], default: str = "") -> str:
    """Ask a question with numbered options."""
    print(f"\n{question}")
    for i, opt in enumerate(options, 1):
        marker = " (default)" if opt == default else ""
        print(f"  {i}. {opt}{marker}")
    while True:
        raw = input("> ").strip()
        if not raw and default:
            return default
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1]
        if raw in options:
            return raw
        print(f"  Please enter 1-{len(options)} or a valid option.")


def _prompt_text(question: str, default: str = "") -> str:
    """Ask for free-text input."""
    suffix = f" [{default}]" if default else ""
    raw = input(f"\n{question}{suffix}\n> ").strip()
    return raw or default


def _detect_inputs() -> dict[str, str]:
    """Auto-detect available scan inputs in the current directory."""
    detected: dict[str, str] = {}

    # Code directory
    if Path("src").is_dir() or Path("package.json").is_file() or Path("requirements.txt").is_file():
        detected["code"] = "."

    # Git repo
    if Path(".git").is_dir():
        detected["repo"] = "."

    # Docker image
    if Path("Dockerfile").is_file() or Path("docker-compose.yml").is_file():
        detected["image"] = "(detected Dockerfile — set IMAGE= manually)"

    # OpenAPI spec
    for candidate in ["openapi.yaml", "openapi.json", "swagger.yaml", "swagger.json",
                       "configs/openapi.yaml", "configs/openapi.json"]:
        if Path(candidate).is_file():
            detected["openapi"] = candidate
            break

    # Binary
    bin_dir = Path("bin")
    if bin_dir.is_dir() and any(bin_dir.iterdir()):
        detected["bin_dir"] = str(bin_dir)

    return detected


def _build_env(config: dict) -> str:
    """Build .env file content from wizard config."""
    lines = [
        "# Generated by orchestrator wizard",
        f"TARGET={config['target']}",
        f"DOMAIN={config['domain']}",
    ]
    if config.get("code"):
        lines.append(f"CODE={config['code']}")
    if config.get("repo"):
        lines.append(f"REPO={config['repo']}")
    if config.get("image"):
        lines.append(f"IMAGE={config['image']}")
    if config.get("rate_limit"):
        lines.append(f"RATE_LIMIT={config['rate_limit']}")
    return "\n".join(lines) + "\n"


def _build_command(config: dict) -> str:
    """Build the make command from wizard config."""
    profile = config["profile"]
    parts = [f"make scan-{profile}"]
    parts.append(f"TARGET={config['target']}")
    parts.append(f"DOMAIN={config['domain']}")
    if config.get("code"):
        parts.append(f"CODE={config['code']}")
    if config.get("repo"):
        parts.append(f"REPO={config['repo']}")
    return " \\\n  ".join(parts)


def main() -> None:
    print("=" * 60)
    print("  Security All-in-One CWE — Scan Configuration Wizard")
    print("=" * 60)

    # 1. Scope
    scope = _prompt(
        "What do you want to scan?",
        ["web", "api", "code", "cloud", "all"],
        default="web",
    )

    # 2. Target
    target = _prompt_text(
        "Target URL (e.g. https://example.com):",
        default="https://httpbin.org",
    )

    # 3. Domain (auto-extracted)
    import re
    domain_match = re.match(r"https?://([^/:]+)", target)
    domain_default = domain_match.group(1) if domain_match else ""
    domain = _prompt_text("Domain:", default=domain_default)

    # 4. Profile
    profile = _prompt(
        "Scan profile?",
        ["light", "medium", "full"],
        default="light" if scope in ("web", "api") else "medium",
    )

    print(f"\n  Profile: {profile}")
    tool_count = len(LIGHT_TOOLS) if profile == "light" else (
        len(MEDIUM_TOOLS) if profile == "medium" else "all"
    )
    print(f"  Tools: {tool_count}")

    # 5. Auto-detect inputs
    detected = _detect_inputs()
    config: dict = {
        "target": target,
        "domain": domain,
        "profile": profile,
        "scope": scope,
        "rate_limit": "50",
    }

    if detected:
        print("\n📂 Detected inputs:")
        for key, val in detected.items():
            print(f"  {key}: {val}")
            if key in ("code", "repo", "bin_dir"):
                config[key] = val

    # 6. Code path (if SAST scope)
    if scope in ("code", "all") and "code" not in config:
        config["code"] = _prompt_text("Source code path:", default=".")

    # 7. Rate limiting
    config["rate_limit"] = _prompt_text("Rate limit (requests/sec):", default="50")

    # 8. Generate .env
    env_content = _build_env(config)
    env_path = Path(".env")
    write_env = _prompt(
        f"Write configuration to {env_path}?",
        ["yes", "no"],
        default="yes",
    )
    if write_env == "yes":
        env_path.write_text(env_content)
        print(f"  ✅ Written to {env_path}")

    # 9. Show command
    cmd = _build_command(config)
    print("\n" + "=" * 60)
    print("  Run this command to start the scan:")
    print("=" * 60)
    print(f"\n  {cmd}\n")

    # 10. Optionally launch
    launch = _prompt("Launch scan now?", ["yes", "no"], default="no")
    if launch == "yes":
        os.execvp("make", ["make", f"scan-{profile}",
                           f"TARGET={config['target']}",
                           f"DOMAIN={config['domain']}"])


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\n\nAborted.")
        sys.exit(1)
